[package]
name = "ws-kipc-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tungstenite = "0.18.0"
tokio-tungstenite = "0.18.0"
futures = "0.3.17"
hyper = { version = "0.14.26", features = ["server","http1"] }
hyper-tungstenite = "0.9.0"
